supabase-community/auth-ui

.changeset/chilly-jars-teach.md, packages/react/src/components/Auth/interfaces/EmailAuth.tsx, packages/react/src/components/UI/Button.tsx
Bug fix
Showing a warning `Received false for a non-boolean attribute loading.`
No longer shows the warning
Add any other context or screenshots.
=> Fix loading prop receiving a non-boolean value

.changeset/chilly-parrots-prove.md, packages/react/package.json, packages/react/src/components/Auth/Auth.tsx, pnpm-lock.yaml
This PR should fix #45 by removing the entire lodash library and using a smaller alternative like just-merge
Include the entire lodash library
No longer includes the entire lodash library and uses just-merge instead
Add any other context or screenshots.
=> Remove lodash and use just-merge instead

.changeset/violet-camels-live.md, packages/react/package.json, packages/react/src/components/Auth/Auth.tsx, packages/react/src/utils.ts, pnpm-lock.yaml
Bug fix for #65 
Error about `merge` not defined with the `just-merge` package
Removed `just-merge` and inline a `merge` function in the package
Add any other context or screenshots.
=> Remove just-merge and add merge function inline

.changeset/cyan-camels-report.md, .changeset/violet-camels-live.md, packages/react/package.json, packages/react/src/components/Auth/Auth.stories.tsx, packages/react/src/components/Auth/Auth.tsx, packages/react/src/utils.ts, pnpm-lock.yaml
Bug fix #66
(see #66) - class names are not applied to email components
Class names properly applied.
See the new storybook story:
I added a story to storybook to demonstrate proper class propagation. I couldn't figure out how to add tests here, but would be nice to have for this case in particular.
=> fixes class names not propagating to email auth components

packages/react/src/components/UI/Container.tsx
Bug fix that closes #40 
Updated container horizontal style to display grid instead of flex.
With 2 Social Auth (fills the whole row)
With 5 Social Auth (fills the whole row)
With many social auth spanning more than a row
With all social auth
P.S. would be nice if this can get the `hacktoberfest-accepted` label later on
=> update container default horizontal style to display as grid

.changeset/few-toes-ring.md, packages/react/common/lib/Localization/en.json, packages/react/src/components/Auth/interfaces/EmailAuth.tsx, packages/react/src/components/UI/Button.tsx, packages/react/src/types.ts
Feature proposal for a small UI change in order to provide a visual feedback to the user while an action (login, registration ...) is performed. I would like to present the "loading state" to the end user by updating the submit button style and label.
Right now nothing happens on the UI once the form is submitted and the end user might think that the app is not working properly.
Once the form is submitted and the internal state is "loading", the button gets styled with less opacity and its label changes to something else more meaningful.
I only implemented this change for the `EmailAuth` component (`sign_in`, `sign_up` views), but if you like the idea I'll do the other forms as well.
=> Feature: UI loading state feedback

packages/react/src/components/Auth/Auth.stories.tsx
React - Auth Examples
When you run `pnpm storybook` the Auth defaults will show unstyled.
Added in default theme for all of the Auth examples.
Linked to #39
=> fix: added ThemeSupa to auth examples

.changeset/tall-chairs-reply.md, packages/react/src/components/Auth/Icons.tsx
Change occurences of the 'clip-rule', 'fill-rule', 'stop-color', 'stop-opacity' SVG attributes to camel-case.
Bug fix. See issue #74.
Some SVG element attributes in [Icons.tsx](https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Icons.tsx) are not camel-cased, as [specified by React](https://reactjs.org/docs/dom-elements.html).
All occurences of the `clip-rule`, `fill-rule`, `stop-color` and `stop-opacity` attributes within [Icons.tsx](https://github.com/supabase/auth-ui/blob/main/packages/react/src/components/Auth/Icons.tsx) have been changed to camel-case.
=> fix: svg icons attribute names

.changeset/breezy-trees-appear.md, packages/react/common/lib/Localization/en.json, packages/react/src/components/Auth/interfaces/EmailAuth.tsx, packages/react/src/types.ts
Feature: add confirmation variable on localization for custom message.
When you press to sign up button, there's a hard-coded message saying "Check your email for the confirmation link."
Now, you can change the message that appears after pressing the sign up button. This was needed since I'm translating all messages to portuguese as needed by my client.
This was discussed on [issue #96](https://github.com/supabase/auth-ui/issues/96) and on [issue #12368](https://github.com/supabase/supabase/discussions/12368#discussioncomment-4951676) on supabase repo
=> feat: add confirmation variable on localization for custom message

packages/solid/src/components/Auth/interfaces/EmailAuth.tsx
This fix is similar to [#128](https://github.com/supabase/auth-ui/pull/128), but for the Solid package.
Passes the `redirectTo` prop when calling `auth.signUp` in `/packages/solid/src/components/Auth/interfaces/EmailAuth.tsx`.
When defining the `redirectTo` prop for sign up, it is currently ignored.
The `redirectTo` prop is now passed to the `auth.signUp` call (via `options.emailRedirectTo`) so that it actually gets used.
None.
=> Pass redirectTo during sign-up in EmailAuth.tsx in Solid package

.changeset/friendly-ants-float.md, packages/react/src/components/Auth/interfaces/EmailAuth.tsx
Fixes https://github.com/supabase/auth-ui/issues/117
Fixes https://github.com/supabase/auth-ui/issues/72
Fixes https://github.com/supabase/auth-ui/issues/76
Doesn't redirect
Redirects to the url provided
Could I get some help testing this change?
=> Add emailRedirectTo to signup in React

.changeset/chatty-crabs-tap.md, packages/react/src/components/Auth/Icons.tsx, packages/solid/src/components/Auth/Icons.tsx, packages/svelte/src/lib/Auth/Icons.svelte
The default styled size of the icons is 21px to make them small enough
to display properly in the button. However the SVG was setup with the
default size of 512px which causes a momentary fash of a large icon as
the page loads. This change sets the default size to 21px.
If a larger size is required in the future it can be overridden through
the styles prop just like the current implementation.
=> bug icon size default change to 21px

packages/svelte/src/lib/Auth/interfaces/EmailAuth.svelte, packages/svelte/src/lib/UI/Button.svelte
Fixes a bug where the button isn't being disabled because the `loading` prop is being passed as is instead of being passed as a value for `disabled`. This also fixes the `EmailAuth` component not passing the `loading` value to it's button.
The button isn't being disabled when the form is submitted, making it look like the form is unresponsive.
The form should now be working as expected.
=> fixed button not being disabled on svelte

.changeset/unlucky-jobs-walk.md, packages/react/src/components/Auth/Auth.tsx, packages/react/src/components/Auth/interfaces/EmailAuth.tsx, packages/react/src/components/Auth/ui/index.tsx, packages/shared/src/types.ts, packages/solid/src/components/Auth/Auth.tsx, packages/solid/src/components/Auth/interfaces/EmailAuth.tsx, packages/solid/src/components/Auth/ui/index.tsx, packages/svelte/src/lib/Auth/Auth.svelte, packages/svelte/src/lib/Auth/interfaces/EmailAuth.svelte, packages/svelte/src/lib/Auth/ui/SignUp.svelte
Fixes #168 by adding a `additionalData` property to the component.
=> Add additional data to components for user_metadata

localization/spanish/es.json
feat(localization): add Spanish translations for sign up, sign in, magic link, forgotten password and update password pages
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
- Add Spanish translation to AuthUI
=> Localization spanish

.changeset/perfect-islands-listen.md, packages/svelte/src/lib/Auth/Auth.svelte
Bug fix: pass the missing `redirectTo` field to `ForgottenPassword` component.
The `redirectTo` field doesn't take effect when the Auth view is FORGOTTEN_PASSWORD. This makes the reset password email link doesn't have `redirectTo` param set as expected.
The reset password email link should have the expected `redirectTo` field set. 
N/A
=> [Fix] pass the missing redirectTo field to ForgottenPassword component

.changeset/tame-mails-act.md, packages/svelte/src/lib/Auth/Auth.svelte
**Bug fix**
Previous behavior: TypeScript shows an error if the `additionalData` prop is not explicitly set on the Svelte [Auth component](https://github.com/supabase/auth-ui/blob/main/packages/svelte/src/lib/Auth/Auth.svelte).
Since `additionalData` is defined as optional in [shared/src/types.ts](https://github.com/supabase/auth-ui/blob/main/packages/shared/src/types.ts#L96) it makes sense to also make it optional for the Svelte Auth component. 
The `additionalData` prop for the Svelte `Auth` component is now optional and doesn't need to be explicitly set. This prevents a scenario like this in TypeScript:
```ts
<script lang="ts">
import { Auth } from '@supabase/auth-ui-svelte'
</script>
<Auth additionalData={undefined} />
```
=> fix(auth-ui-svelte): make additionalData prop optional

.changeset/dry-candles-roll.md, packages/react/src/components/UI/Input.tsx, packages/solid/src/components/UI/Input.tsx, packages/svelte/src/lib/UI/Input.svelte
Feature - Password letter spacing
Letter spacing seem odd and too spaced out
letter-spacing now set to 0px
Closes #198
=> feat: password letter spacing

.changeset/selfish-crews-tie.md, packages/react/src/components/Auth/Auth.tsx, packages/react/src/components/Auth/interfaces/ForgottenPassword.tsx
Bug fix/enhancement
Switching between login and forgot password views alters the layout alignment.
https://github.com/supabase/auth-ui/assets/22655069/918a936b-2f46-41d1-b2f2-a72cb665140a
Closes #199
=> fix: view layout alignment 

.changeset/pretty-pumpkins-admire.md, packages/react/src/components/Auth/interfaces/MagicLink.tsx, packages/shared/src/types.ts
Bug Fix
If you have a blank email address you can still send a request for a magic link and a system error appears.
Now instead of the system error you get an empty email error and also no request is sent:
https://github.com/supabase/auth-ui/assets/22655069/416e7aee-9226-4ea6-a0b8-c60f201c34dc
Closes #179
=> fix: check for blank email address on magic links

packages/react/src/components/Auth/Icons.tsx, packages/react/src/components/Auth/interfaces/SocialAuth.tsx
Adding in the linkedin logo and fixing the display name when using the new LinkedIn  OIDC provider
Currently it looks like this with the new provider
Which is not ideal
In the react example it now looks like this running in dev:
The same way it looks with the old provider
There is an issue filed for this here:
https://github.com/supabase/auth-ui/issues/234
This is my first pull request here, I've tried to follow the guidelines but apologies if I've not stuck to protocol in some way
=> Linkedin OIDC Logo and title in react auth

packages/react/src/components/Auth/Auth.tsx, packages/react/src/components/Auth/interfaces/EmailAuth.tsx, packages/react/src/components/Auth/interfaces/UpdatePassword.tsx, packages/shared/src/types.ts, packages/solid/src/components/Auth/Auth.tsx, packages/solid/src/components/Auth/interfaces/EmailAuth.tsx, packages/solid/src/components/Auth/interfaces/UpdatePassword.tsx, packages/svelte/src/lib/Auth/Auth.svelte, packages/svelte/src/lib/Auth/interfaces/EmailAuth.svelte, packages/svelte/src/lib/Auth/interfaces/UpdatePassword.svelte, packages/svelte/src/lib/Auth/ui/SignUp.svelte, packages/svelte/src/lib/Auth/ui/UpdatePassword.svelte
Feat/Bug fix
Their is a 72 character length password in the sign up with Supabase that is not captured in Auth UI.
Instead of setting this as a mandatory option I've added a prop in which users can turn on or off if they want to turn on the password limit.
Closes #187
=> feat: password limit prop

README.md
As per internal discussion, the team does not have the capacity to provide the due care and concern required for this repository. Additionally, our recommended approach to authentication has changed since creation of Auth UI and we will need time to revisit construct
As such, we'll be moving bulk of this repository from Supabase to Supabase-Community and potentially expanding on a few core Templates within the Next.js ecosystem.
For now, please visit the our guides on [Server Side Rendering](https://supabase.com/docs/guides/auth/server-side/overview) and the @supabase/ssr for further details on implementing Auth with Supabase.
=> docs: add notice of movement of Auth UI from Supabase to Supabase-Community

packages/react/package.json, packages/shared/package.json, packages/solid/package.json, packages/svelte/package.json
Upgrade supabase js version to v2.39.3. This includes a fix on the [`PASSWORD_RECOVERY` event](https://github.com/supabase/gotrue-js/pull/829) which might help with some of the issues
=> feat: bump supabase js version to v2.39.3
